-- Fase 1: modelo de datos del negocio.
-- Tipos de producto, personalización (técnicas, zonas, diseños subidos), escalas de
-- mayoreo, direcciones, métodos de envío, pedidos con su reparto por talla y color,
-- historial de estados y pagos. Incluye los datos semilla de los catálogos.

-- =====================================================================================
-- 1. Catálogo: tipos de producto
-- =====================================================================================

CREATE TABLE product_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(30) NOT NULL UNIQUE,
    name VARCHAR(80) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT product_types_code_format CHECK (code ~ '^[A-Z][A-Z0-9_]*$'),
    CONSTRAINT product_types_name_not_blank CHECK (length(btrim(name)) > 0)
);

ALTER TABLE products ADD COLUMN product_type_id BIGINT REFERENCES product_types(id) ON DELETE RESTRICT;
ALTER TABLE products ADD COLUMN is_customizable BOOLEAN NOT NULL DEFAULT FALSE;
-- Solo se personaliza un producto cuyo tipo define zonas de impresión.
ALTER TABLE products ADD CONSTRAINT products_customizable_needs_type
    CHECK (NOT is_customizable OR product_type_id IS NOT NULL);

CREATE INDEX products_product_type_id_idx ON products (product_type_id);

-- =====================================================================================
-- 2. Personalización
-- =====================================================================================

CREATE TABLE customization_techniques (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(30) NOT NULL UNIQUE,
    name VARCHAR(80) NOT NULL,
    description TEXT,
    base_cost NUMERIC(12, 2) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT techniques_code_format CHECK (code ~ '^[A-Z][A-Z0-9_]*$'),
    CONSTRAINT techniques_name_not_blank CHECK (length(btrim(name)) > 0),
    CONSTRAINT techniques_base_cost_nonnegative CHECK (base_cost >= 0)
);

CREATE TABLE print_zones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(30) NOT NULL UNIQUE,
    name VARCHAR(80) NOT NULL,
    CONSTRAINT print_zones_code_format CHECK (code ~ '^[A-Z][A-Z0-9_]*$'),
    CONSTRAINT print_zones_name_not_blank CHECK (length(btrim(name)) > 0)
);

-- Qué zona admite qué técnica en cada tipo de producto, con su tamaño máximo, su recargo
-- y el recuadro (en % de la imagen del producto) donde se dibuja la vista previa.
CREATE TABLE product_type_zones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_type_id BIGINT NOT NULL REFERENCES product_types(id) ON DELETE RESTRICT,
    zone_id BIGINT NOT NULL REFERENCES print_zones(id) ON DELETE RESTRICT,
    technique_id BIGINT NOT NULL REFERENCES customization_techniques(id) ON DELETE RESTRICT,
    max_width_cm NUMERIC(5, 1) NOT NULL,
    max_height_cm NUMERIC(5, 1) NOT NULL,
    surcharge NUMERIC(12, 2) NOT NULL,
    preview_x NUMERIC(5, 2) NOT NULL,
    preview_y NUMERIC(5, 2) NOT NULL,
    preview_w NUMERIC(5, 2) NOT NULL,
    preview_h NUMERIC(5, 2) NOT NULL,
    CONSTRAINT type_zones_unique UNIQUE (product_type_id, zone_id, technique_id),
    CONSTRAINT type_zones_size_positive CHECK (max_width_cm > 0 AND max_height_cm > 0),
    CONSTRAINT type_zones_surcharge_nonnegative CHECK (surcharge >= 0),
    CONSTRAINT type_zones_preview_origin CHECK (preview_x >= 0 AND preview_y >= 0),
    CONSTRAINT type_zones_preview_size CHECK (preview_w > 0 AND preview_h > 0),
    CONSTRAINT type_zones_preview_inside CHECK (preview_x + preview_w <= 100 AND preview_y + preview_h <= 100)
);

CREATE INDEX type_zones_zone_id_idx ON product_type_zones (zone_id);
CREATE INDEX type_zones_technique_id_idx ON product_type_zones (technique_id);

-- Imágenes del cliente. Se guardan en la base porque el disco de Railway es efímero (D7).
CREATE TABLE design_uploads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    original_filename VARCHAR(255) NOT NULL,
    content_type VARCHAR(30) NOT NULL,
    size_bytes INTEGER NOT NULL,
    sha256 CHAR(64) NOT NULL,
    data BYTEA NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT design_uploads_filename_not_blank CHECK (length(btrim(original_filename)) > 0),
    CONSTRAINT design_uploads_content_type_valid CHECK (content_type IN ('image/png', 'image/jpeg')),
    CONSTRAINT design_uploads_size_valid CHECK (size_bytes BETWEEN 1 AND 5242880),
    CONSTRAINT design_uploads_size_matches_data CHECK (octet_length(data) = size_bytes),
    CONSTRAINT design_uploads_sha256_format CHECK (sha256 ~ '^[0-9a-f]{64}$')
);

CREATE INDEX design_uploads_user_created_idx ON design_uploads (user_id, created_at DESC);
CREATE INDEX design_uploads_user_sha256_idx ON design_uploads (user_id, sha256);

-- =====================================================================================
-- 3. Mayoreo (D2): se aplica la escala con mayor min_quantity <= cantidad del diseño
-- =====================================================================================

CREATE TABLE quantity_tiers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    min_quantity INTEGER NOT NULL UNIQUE,
    label VARCHAR(60) NOT NULL,
    discount_percent NUMERIC(5, 2) NOT NULL,
    CONSTRAINT tiers_min_quantity_positive CHECK (min_quantity >= 1),
    CONSTRAINT tiers_label_not_blank CHECK (length(btrim(label)) > 0),
    CONSTRAINT tiers_discount_range CHECK (discount_percent >= 0 AND discount_percent < 100)
);

-- =====================================================================================
-- 4. Entrega
-- =====================================================================================

CREATE TABLE addresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    receiver_name VARCHAR(160) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    department VARCHAR(60) NOT NULL,
    province VARCHAR(60) NOT NULL,
    district VARCHAR(60) NOT NULL,
    street VARCHAR(200) NOT NULL,
    reference VARCHAR(200),
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT addresses_receiver_not_blank CHECK (length(btrim(receiver_name)) > 0),
    CONSTRAINT addresses_phone_format CHECK (phone ~ '^\+?[0-9 ]{6,20}$'),
    CONSTRAINT addresses_department_not_blank CHECK (length(btrim(department)) > 0),
    CONSTRAINT addresses_province_not_blank CHECK (length(btrim(province)) > 0),
    CONSTRAINT addresses_district_not_blank CHECK (length(btrim(district)) > 0),
    CONSTRAINT addresses_street_not_blank CHECK (length(btrim(street)) > 0)
);

CREATE INDEX addresses_user_id_idx ON addresses (user_id);
CREATE UNIQUE INDEX addresses_one_default_per_user ON addresses (user_id) WHERE is_default;

-- requires_address = FALSE en el recojo en tienda: el pedido no lleva dirección.
CREATE TABLE shipping_methods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(30) NOT NULL UNIQUE,
    name VARCHAR(80) NOT NULL,
    cost NUMERIC(12, 2) NOT NULL,
    estimated_days INTEGER NOT NULL,
    requires_address BOOLEAN NOT NULL DEFAULT TRUE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT shipping_code_format CHECK (code ~ '^[A-Z][A-Z0-9_]*$'),
    CONSTRAINT shipping_name_not_blank CHECK (length(btrim(name)) > 0),
    CONSTRAINT shipping_cost_nonnegative CHECK (cost >= 0),
    CONSTRAINT shipping_days_nonnegative CHECK (estimated_days >= 0)
);

-- =====================================================================================
-- 5. Pedidos: se recrean orders y order_items (V1), que ningún flujo usaba
-- =====================================================================================

DROP TABLE order_items;
DROP TABLE orders;

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_code VARCHAR(20) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE_PAGO',
    subtotal NUMERIC(12, 2) NOT NULL,
    discount_amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
    shipping_cost NUMERIC(12, 2) NOT NULL DEFAULT 0,
    total_amount NUMERIC(12, 2) NOT NULL,
    shipping_method_id BIGINT NOT NULL REFERENCES shipping_methods(id) ON DELETE RESTRICT,
    -- Copia de la dirección: el pedido no cambia si el cliente edita su libreta.
    receiver_name VARCHAR(160) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    department VARCHAR(60),
    province VARCHAR(60),
    district VARCHAR(60),
    street VARCHAR(200),
    reference VARCHAR(200),
    customer_note VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT orders_code_not_blank CHECK (length(btrim(order_code)) > 0),
    CONSTRAINT orders_status_valid CHECK (status IN ('PENDIENTE_PAGO', 'PAGADO', 'EN_PRODUCCION',
        'LISTO_PARA_ENVIO', 'ENVIADO', 'ENTREGADO', 'CANCELADO')),
    CONSTRAINT orders_amounts_nonnegative CHECK (subtotal >= 0 AND discount_amount >= 0
        AND shipping_cost >= 0 AND total_amount >= 0),
    CONSTRAINT orders_discount_within_subtotal CHECK (discount_amount <= subtotal),
    CONSTRAINT orders_total_consistent CHECK (total_amount = subtotal - discount_amount + shipping_cost),
    CONSTRAINT orders_receiver_not_blank CHECK (length(btrim(receiver_name)) > 0),
    -- La dirección va completa o no va (recojo en tienda).
    CONSTRAINT orders_address_complete CHECK (
        (department IS NULL AND province IS NULL AND district IS NULL AND street IS NULL AND reference IS NULL)
        OR (department IS NOT NULL AND province IS NOT NULL AND district IS NOT NULL AND street IS NOT NULL))
);

CREATE INDEX orders_user_created_idx ON orders (user_id, created_at DESC);
CREATE INDEX orders_status_idx ON orders (status);
CREATE INDEX orders_shipping_method_id_idx ON orders (shipping_method_id);

-- Una línea = un diseño sobre un producto (D3). Los precios quedan congelados.
CREATE TABLE order_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
    product_name VARCHAR(180) NOT NULL,
    technique_id BIGINT REFERENCES customization_techniques(id) ON DELETE RESTRICT,
    design_upload_id BIGINT REFERENCES design_uploads(id) ON DELETE RESTRICT,
    quantity_total INTEGER NOT NULL,
    tier_min_quantity INTEGER NOT NULL,
    unit_base_price NUMERIC(12, 2) NOT NULL,
    unit_customization_price NUMERIC(12, 2) NOT NULL DEFAULT 0,
    discount_percent NUMERIC(5, 2) NOT NULL DEFAULT 0,
    line_total NUMERIC(12, 2) NOT NULL,
    CONSTRAINT order_lines_product_name_not_blank CHECK (length(btrim(product_name)) > 0),
    -- Técnica y diseño van juntos: o la línea está personalizada o no lo está.
    CONSTRAINT order_lines_customization_complete CHECK ((technique_id IS NULL) = (design_upload_id IS NULL)),
    CONSTRAINT order_lines_no_cost_without_design CHECK (technique_id IS NOT NULL OR unit_customization_price = 0),
    CONSTRAINT order_lines_quantity_positive CHECK (quantity_total > 0),
    CONSTRAINT order_lines_tier_reached CHECK (tier_min_quantity >= 1 AND tier_min_quantity <= quantity_total),
    CONSTRAINT order_lines_prices_nonnegative CHECK (unit_base_price >= 0 AND unit_customization_price >= 0
        AND line_total >= 0),
    CONSTRAINT order_lines_discount_range CHECK (discount_percent >= 0 AND discount_percent < 100)
);

CREATE INDEX order_lines_order_id_idx ON order_lines (order_id);
CREATE INDEX order_lines_product_id_idx ON order_lines (product_id);
CREATE INDEX order_lines_design_upload_id_idx ON order_lines (design_upload_id);

-- Zonas elegidas para la línea, con el recargo vigente al comprar.
CREATE TABLE order_line_zones (
    order_line_id BIGINT NOT NULL REFERENCES order_lines(id) ON DELETE CASCADE,
    zone_id BIGINT NOT NULL REFERENCES print_zones(id) ON DELETE RESTRICT,
    surcharge NUMERIC(12, 2) NOT NULL,
    PRIMARY KEY (order_line_id, zone_id),
    CONSTRAINT order_line_zones_surcharge_nonnegative CHECK (surcharge >= 0)
);

CREATE INDEX order_line_zones_zone_id_idx ON order_line_zones (zone_id);

-- Reparto de la línea entre tallas y colores. Que la suma de quantity sea igual a
-- order_lines.quantity_total lo valida el Service al crear el pedido.
CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_line_id BIGINT NOT NULL REFERENCES order_lines(id) ON DELETE CASCADE,
    variant_id BIGINT NOT NULL REFERENCES product_variants(id) ON DELETE RESTRICT,
    sku VARCHAR(80) NOT NULL,
    size_name VARCHAR(30) NOT NULL,
    color_name VARCHAR(60) NOT NULL,
    quantity INTEGER NOT NULL,
    CONSTRAINT order_items_line_variant_unique UNIQUE (order_line_id, variant_id),
    CONSTRAINT order_items_quantity_positive CHECK (quantity > 0)
);

CREATE INDEX order_items_variant_id_idx ON order_items (variant_id);

CREATE TABLE order_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    from_status VARCHAR(20),
    to_status VARCHAR(20) NOT NULL,
    changed_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    comment VARCHAR(500),
    changed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT status_history_from_valid CHECK (from_status IS NULL OR from_status IN ('PENDIENTE_PAGO',
        'PAGADO', 'EN_PRODUCCION', 'LISTO_PARA_ENVIO', 'ENVIADO', 'ENTREGADO', 'CANCELADO')),
    CONSTRAINT status_history_to_valid CHECK (to_status IN ('PENDIENTE_PAGO', 'PAGADO', 'EN_PRODUCCION',
        'LISTO_PARA_ENVIO', 'ENVIADO', 'ENTREGADO', 'CANCELADO')),
    CONSTRAINT status_history_changes CHECK (from_status IS DISTINCT FROM to_status)
);

CREATE INDEX status_history_order_changed_idx ON order_status_history (order_id, changed_at);

-- provider sin lista cerrada: la pasarela real (fase 6) se agrega sin alterar la tabla.
CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE RESTRICT,
    provider VARCHAR(30) NOT NULL,
    provider_reference VARCHAR(120) NOT NULL UNIQUE,
    amount NUMERIC(12, 2) NOT NULL,
    currency CHAR(3) NOT NULL DEFAULT 'PEN',
    status VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    confirmed_at TIMESTAMPTZ,
    CONSTRAINT payments_provider_format CHECK (provider ~ '^[A-Z][A-Z0-9_]*$'),
    CONSTRAINT payments_reference_not_blank CHECK (length(btrim(provider_reference)) > 0),
    CONSTRAINT payments_amount_positive CHECK (amount > 0),
    CONSTRAINT payments_currency_format CHECK (currency ~ '^[A-Z]{3}$'),
    CONSTRAINT payments_status_valid CHECK (status IN ('PENDIENTE', 'APROBADO', 'RECHAZADO')),
    CONSTRAINT payments_approved_has_date CHECK (status <> 'APROBADO' OR confirmed_at IS NOT NULL)
);

CREATE INDEX payments_order_id_idx ON payments (order_id);
-- Un pedido se paga una sola vez.
CREATE UNIQUE INDEX payments_one_approved_per_order ON payments (order_id) WHERE status = 'APROBADO';

-- =====================================================================================
-- 6. Datos semilla
-- =====================================================================================

INSERT INTO product_types (code, name) VALUES
    ('POLO', 'Polo'),
    ('POLERA', 'Polera'),
    ('GORRA', 'Gorra'),
    ('TOTE', 'Tote bag');

INSERT INTO customization_techniques (code, name, description, base_cost) VALUES
    ('ESTAMPADO', 'Estampado', 'Impresión DTF a todo color. Admite todas las zonas y formatos grandes.', 8.00),
    ('BORDADO', 'Bordado', 'Bordado a hilo. Solo zonas pequeñas, con acabado en relieve y mayor durabilidad.', 15.00);

INSERT INTO print_zones (code, name) VALUES
    ('PECHO_IZQ', 'Pecho izquierdo'),
    ('PECHO_CENTRO', 'Pecho centro'),
    ('ESPALDA', 'Espalda'),
    ('MANGA_IZQ', 'Manga izquierda'),
    ('MANGA_DER', 'Manga derecha'),
    ('GORRA_FRENTE', 'Frente de la gorra'),
    ('GORRA_LATERAL', 'Lateral de la gorra'),
    ('TOTE_CARA_A', 'Cara A del tote'),
    ('TOTE_CARA_B', 'Cara B del tote');

-- El bordado admite menos zonas y tamaños más chicos que el estampado (D4).
INSERT INTO product_type_zones (product_type_id, zone_id, technique_id, max_width_cm, max_height_cm,
                                surcharge, preview_x, preview_y, preview_w, preview_h)
SELECT pt.id, z.id, t.id, v.max_width_cm, v.max_height_cm, v.surcharge,
       v.preview_x, v.preview_y, v.preview_w, v.preview_h
FROM (VALUES
    ('POLO',   'PECHO_IZQ',     'ESTAMPADO', 10.0, 10.0,  5.00, 56.00, 28.00, 12.00, 12.00),
    ('POLO',   'PECHO_CENTRO',  'ESTAMPADO', 28.0, 35.0, 12.00, 33.00, 28.00, 34.00, 40.00),
    ('POLO',   'ESPALDA',       'ESTAMPADO', 30.0, 40.0, 15.00, 32.00, 22.00, 36.00, 46.00),
    ('POLO',   'MANGA_IZQ',     'ESTAMPADO',  8.0,  8.0,  4.00, 80.00, 24.00,  9.00,  9.00),
    ('POLO',   'MANGA_DER',     'ESTAMPADO',  8.0,  8.0,  4.00, 11.00, 24.00,  9.00,  9.00),
    ('POLO',   'PECHO_IZQ',     'BORDADO',    9.0,  9.0,  8.00, 56.00, 28.00, 11.00, 11.00),
    ('POLO',   'MANGA_IZQ',     'BORDADO',    7.0,  7.0,  6.00, 80.00, 24.00,  8.00,  8.00),
    ('POLO',   'MANGA_DER',     'BORDADO',    7.0,  7.0,  6.00, 12.00, 24.00,  8.00,  8.00),
    ('POLERA', 'PECHO_IZQ',     'ESTAMPADO', 10.0, 10.0,  5.00, 56.00, 30.00, 12.00, 12.00),
    ('POLERA', 'PECHO_CENTRO',  'ESTAMPADO', 28.0, 30.0, 12.00, 33.00, 32.00, 34.00, 34.00),
    ('POLERA', 'ESPALDA',       'ESTAMPADO', 30.0, 40.0, 15.00, 32.00, 24.00, 36.00, 46.00),
    ('POLERA', 'MANGA_IZQ',     'ESTAMPADO',  8.0, 20.0,  6.00, 82.00, 34.00,  8.00, 22.00),
    ('POLERA', 'MANGA_DER',     'ESTAMPADO',  8.0, 20.0,  6.00, 10.00, 34.00,  8.00, 22.00),
    ('POLERA', 'PECHO_IZQ',     'BORDADO',    9.0,  9.0,  8.00, 56.00, 30.00, 11.00, 11.00),
    ('POLERA', 'MANGA_IZQ',     'BORDADO',    7.0,  7.0,  6.00, 82.00, 34.00,  8.00,  8.00),
    ('POLERA', 'MANGA_DER',     'BORDADO',    7.0,  7.0,  6.00, 10.00, 34.00,  8.00,  8.00),
    ('GORRA',  'GORRA_FRENTE',  'ESTAMPADO', 12.0,  6.0,  6.00, 32.00, 30.00, 36.00, 18.00),
    ('GORRA',  'GORRA_LATERAL', 'ESTAMPADO',  6.0,  4.0,  4.00, 70.00, 40.00, 14.00, 10.00),
    ('GORRA',  'GORRA_FRENTE',  'BORDADO',   10.0,  5.0,  9.00, 34.00, 30.00, 32.00, 16.00),
    ('GORRA',  'GORRA_LATERAL', 'BORDADO',    5.0,  4.0,  6.00, 70.00, 40.00, 12.00, 10.00),
    ('TOTE',   'TOTE_CARA_A',   'ESTAMPADO', 30.0, 35.0, 12.00, 22.00, 34.00, 56.00, 52.00),
    ('TOTE',   'TOTE_CARA_B',   'ESTAMPADO', 30.0, 35.0, 12.00, 22.00, 34.00, 56.00, 52.00),
    ('TOTE',   'TOTE_CARA_A',   'BORDADO',   20.0, 20.0, 15.00, 32.00, 44.00, 36.00, 36.00)
) AS v (type_code, zone_code, technique_code, max_width_cm, max_height_cm,
        surcharge, preview_x, preview_y, preview_w, preview_h)
JOIN product_types pt ON pt.code = v.type_code
JOIN print_zones z ON z.code = v.zone_code
JOIN customization_techniques t ON t.code = v.technique_code;

INSERT INTO quantity_tiers (min_quantity, label, discount_percent) VALUES
    (1, 'Unidad', 0.00),
    (3, 'Paquete de 3', 5.00),
    (6, 'Paquete de 6', 10.00),
    (12, 'Docena', 15.00);

INSERT INTO shipping_methods (code, name, cost, estimated_days, requires_address) VALUES
    ('LIMA_METROPOLITANA', 'Envío a Lima Metropolitana', 10.00, 2, TRUE),
    ('PROVINCIAS', 'Envío a provincias', 20.00, 5, TRUE),
    ('RECOJO_TIENDA', 'Recojo en tienda', 0.00, 1, FALSE);

-- Productos existentes: se les asigna un tipo según su nombre. Los que no encajan en
-- ninguno quedan sin tipo y no personalizables, hasta que el administrador los clasifique.
UPDATE products SET product_type_id = (SELECT id FROM product_types WHERE code = 'POLERA')
WHERE product_type_id IS NULL AND name ~* '(polera|hoodie|sudadera|buzo)';

UPDATE products SET product_type_id = (SELECT id FROM product_types WHERE code = 'POLO')
WHERE product_type_id IS NULL AND name ~* '(polo|camiseta|t-?shirt|remera)';

UPDATE products SET product_type_id = (SELECT id FROM product_types WHERE code = 'GORRA')
WHERE product_type_id IS NULL AND name ~* '(gorra|gorro|cap\M)';

UPDATE products SET product_type_id = (SELECT id FROM product_types WHERE code = 'TOTE')
WHERE product_type_id IS NULL AND name ~* '(tote|bolsa|bolso)';

UPDATE products SET is_customizable = TRUE WHERE product_type_id IS NOT NULL;
