# -*- coding: utf-8 -*-
"""
Modelo de datos de Coral Shop.

Fuente de verdad única del esquema: la usan tanto el generador de figuras
(diagramas entidad-relación) como el generador del informe (diccionario de campos).

Cada campo es una tupla: (nombre, tipo, llave, descripción)
  llave: 'PK' | 'FK -> tabla.campo' | 'UQ' | 'UQ*' (única compuesta) | ''
"""

MODULOS = {
    "seguridad": ("Seguridad y usuarios", "#6D2E46"),
    "catalogo": ("Catálogo e inventario", "#3C6E8F"),
    "personalizacion": ("Personalización de estampado", "#A26769"),
    "compra": ("Carrito, pedidos y pagos", "#4E7A5A"),
    "soporte": ("Soporte y trazabilidad", "#8A6D3B"),
}

TABLAS = [
    # ------------------------------------------------------------------ seguridad
    dict(nombre="role", modulo="seguridad",
         desc="Catálogo de roles del sistema. Determina qué operaciones puede ejecutar un usuario.",
         campos=[
             ("id", "SERIAL", "PK", "Identificador del rol."),
             ("name", "VARCHAR(30)", "UQ", "ADMIN, VENDEDOR, DISENADOR o CLIENTE."),
             ("description", "VARCHAR(150)", "", "Descripción funcional del rol."),
             ("is_active", "BOOLEAN", "", "Permite desactivar un rol sin borrarlo."),
             ("created_at", "TIMESTAMP", "", "Fecha de creación del registro."),
         ]),
    dict(nombre="app_user", modulo="seguridad",
         desc="Clientes y personal de la tienda. Una sola tabla de usuarios diferenciada por rol.",
         campos=[
             ("id", "SERIAL", "PK", "Identificador del usuario."),
             ("first_name", "VARCHAR(60)", "", "Nombres."),
             ("last_name", "VARCHAR(60)", "", "Apellidos."),
             ("email", "VARCHAR(120)", "UQ", "Correo, sirve como credencial de acceso."),
             ("password_hash", "VARCHAR(72)", "", "Hash BCrypt de la contraseña. Nunca texto plano."),
             ("phone", "VARCHAR(15)", "", "Teléfono de contacto."),
             ("birth_date", "DATE", "", "Fecha de nacimiento, usada para segmentar campañas."),
             ("role_id", "INT", "FK -> role.id", "Rol asignado."),
             ("is_active", "BOOLEAN", "", "Baja lógica de la cuenta."),
             ("email_verified", "BOOLEAN", "", "Indica si el correo fue confirmado."),
             ("created_at", "TIMESTAMP", "", "Fecha de registro."),
             ("updated_at", "TIMESTAMP", "", "Fecha de la última modificación."),
         ]),
    dict(nombre="address", modulo="seguridad",
         desc="Libreta de direcciones del cliente. Un usuario puede guardar varias direcciones.",
         campos=[
             ("id", "SERIAL", "PK", "Identificador de la dirección."),
             ("user_id", "INT", "FK -> app_user.id", "Dueño de la dirección."),
             ("alias", "VARCHAR(40)", "", "Etiqueta libre: Casa, Trabajo, Universidad."),
             ("receiver_name", "VARCHAR(120)", "", "Persona que recibe el paquete."),
             ("phone", "VARCHAR(15)", "", "Teléfono de quien recibe."),
             ("department", "VARCHAR(60)", "", "Departamento."),
             ("province", "VARCHAR(60)", "", "Provincia."),
             ("district", "VARCHAR(60)", "", "Distrito."),
             ("street", "VARCHAR(160)", "", "Calle y número."),
             ("reference", "VARCHAR(160)", "", "Referencia para el repartidor."),
             ("is_default", "BOOLEAN", "", "Dirección sugerida por defecto en el checkout."),
         ]),
    dict(nombre="password_reset_token", modulo="seguridad",
         desc="Tokens de un solo uso para el flujo de recuperación de contraseña.",
         campos=[
             ("id", "SERIAL", "PK", "Identificador del token."),
             ("user_id", "INT", "FK -> app_user.id", "Usuario que solicitó el reinicio."),
             ("token", "VARCHAR(64)", "UQ", "Token aleatorio enviado al correo."),
             ("expires_at", "TIMESTAMP", "", "Vencimiento (30 minutos)."),
             ("used_at", "TIMESTAMP", "", "Momento en que se consumió; NULL si sigue vigente."),
         ]),

    # ------------------------------------------------------------------- catalogo
    dict(nombre="category", modulo="catalogo",
         desc="Árbol de categorías del catálogo. Se autorreferencia para permitir subcategorías.",
         campos=[
             ("id", "SERIAL", "PK", "Identificador de la categoría."),
             ("parent_id", "INT", "FK -> category.id", "Categoría padre; NULL si es raíz."),
             ("name", "VARCHAR(60)", "", "Nombre visible: Polos, Poleras, Gorras, Tote bags."),
             ("slug", "VARCHAR(60)", "UQ", "Identificador para la URL amigable."),
             ("description", "VARCHAR(250)", "", "Texto descriptivo de la categoría."),
             ("image_url", "VARCHAR(250)", "", "Imagen de portada."),
             ("display_order", "INT", "", "Orden de aparición en el menú."),
             ("is_active", "BOOLEAN", "", "Permite ocultar la categoría sin borrarla."),
         ]),
    dict(nombre="product", modulo="catalogo",
         desc="Modelo base de una prenda. No tiene stock: el stock vive en sus variantes.",
         campos=[
             ("id", "SERIAL", "PK", "Identificador del producto."),
             ("category_id", "INT", "FK -> category.id", "Categoría a la que pertenece."),
             ("name", "VARCHAR(120)", "", "Nombre comercial de la prenda."),
             ("slug", "VARCHAR(120)", "UQ", "Identificador para la URL amigable."),
             ("description", "TEXT", "", "Descripción, composición y cuidados."),
             ("base_price", "NUMERIC(10,2)", "", "Precio de la prenda sin estampado."),
             ("gender", "VARCHAR(10)", "", "HOMBRE, MUJER o UNISEX."),
             ("is_customizable", "BOOLEAN", "", "Habilita el personalizador de estampado."),
             ("avg_rating", "NUMERIC(2,1)", "", "Promedio de calificaciones, recalculado por trigger."),
             ("is_active", "BOOLEAN", "", "Baja lógica del producto."),
             ("created_at", "TIMESTAMP", "", "Fecha de alta."),
             ("updated_at", "TIMESTAMP", "", "Fecha de la última modificación."),
         ]),
    dict(nombre="product_image", modulo="catalogo",
         desc="Galería de imágenes de un producto.",
         campos=[
             ("id", "SERIAL", "PK", "Identificador de la imagen."),
             ("product_id", "INT", "FK -> product.id", "Producto al que pertenece."),
             ("url", "VARCHAR(250)", "", "Ruta del archivo."),
             ("alt_text", "VARCHAR(120)", "", "Texto alternativo (accesibilidad)."),
             ("display_order", "INT", "", "Orden dentro de la galería."),
             ("is_primary", "BOOLEAN", "", "Marca la imagen que se muestra en el listado."),
         ]),
    dict(nombre="size", modulo="catalogo",
         desc="Catálogo maestro de tallas.",
         campos=[
             ("id", "SERIAL", "PK", "Identificador de la talla."),
             ("code", "VARCHAR(6)", "UQ", "XS, S, M, L, XL, XXL."),
             ("label", "VARCHAR(30)", "", "Descripción y medidas de referencia."),
             ("display_order", "INT", "", "Orden natural de la talla."),
         ]),
    dict(nombre="color", modulo="catalogo",
         desc="Catálogo maestro de colores de prenda.",
         campos=[
             ("id", "SERIAL", "PK", "Identificador del color."),
             ("name", "VARCHAR(30)", "UQ", "Nombre comercial: Negro, Blanco, Coral."),
             ("hex_code", "CHAR(7)", "", "Código hexadecimal para pintar el selector."),
             ("display_order", "INT", "", "Orden de aparición."),
         ]),
    dict(nombre="product_variant", modulo="catalogo",
         desc="Artículo físico real: la combinación producto + talla + color. Es lo que tiene stock y SKU.",
         campos=[
             ("id", "SERIAL", "PK", "Identificador de la variante."),
             ("product_id", "INT", "FK -> product.id", "Producto base."),
             ("size_id", "INT", "FK -> size.id", "Talla."),
             ("color_id", "INT", "FK -> color.id", "Color."),
             ("sku", "VARCHAR(30)", "UQ", "Código único de almacén, generado como PRD-TALLA-COLOR."),
             ("stock", "INT", "", "Unidades disponibles. CHECK (stock >= 0)."),
             ("reserved_stock", "INT", "", "Unidades comprometidas por pedidos no despachados."),
             ("min_stock", "INT", "", "Umbral que dispara la alerta de reposición."),
             ("price_override", "NUMERIC(10,2)", "", "Precio propio de la variante; NULL usa base_price."),
             ("is_active", "BOOLEAN", "", "Baja lógica de la variante."),
         ],
         restricciones=["UNIQUE (product_id, size_id, color_id)"]),
    dict(nombre="inventory_movement", modulo="catalogo",
         desc="Kardex: toda entrada, salida o ajuste de stock queda registrada aquí.",
         campos=[
             ("id", "BIGSERIAL", "PK", "Identificador del movimiento."),
             ("variant_id", "INT", "FK -> product_variant.id", "Variante afectada."),
             ("movement_type", "VARCHAR(12)", "", "INGRESO, SALIDA, AJUSTE, RESERVA o LIBERACION."),
             ("quantity", "INT", "", "Cantidad del movimiento (positiva)."),
             ("previous_stock", "INT", "", "Stock antes del movimiento."),
             ("new_stock", "INT", "", "Stock después del movimiento."),
             ("reason", "VARCHAR(150)", "", "Motivo declarado del ajuste."),
             ("order_id", "INT", "FK -> orders.id", "Pedido que originó el movimiento, si aplica."),
             ("user_id", "INT", "FK -> app_user.id", "Usuario responsable."),
             ("created_at", "TIMESTAMP", "", "Fecha y hora del movimiento."),
         ]),

    # ------------------------------------------------------------ personalizacion
    dict(nombre="print_technique", modulo="personalizacion",
         desc="Técnicas de estampado ofrecidas y su costo base.",
         campos=[
             ("id", "SERIAL", "PK", "Identificador de la técnica."),
             ("name", "VARCHAR(40)", "UQ", "DTF, Serigrafía, Vinil textil o Bordado."),
             ("description", "VARCHAR(200)", "", "En que consiste y para que sirve."),
             ("base_cost", "NUMERIC(10,2)", "", "Costo base que se suma al precio de la prenda."),
             ("max_colors", "INT", "", "Límite de colores que admite la técnica."),
             ("is_active", "BOOLEAN", "", "Permite retirar la técnica de la oferta."),
         ]),
    dict(nombre="print_zone", modulo="personalizacion",
         desc="Zonas de la prenda donde se puede estampar.",
         campos=[
             ("id", "SERIAL", "PK", "Identificador de la zona."),
             ("name", "VARCHAR(40)", "UQ", "Pecho frontal, Espalda completa, Manga o Pecho izquierdo."),
             ("extra_cost", "NUMERIC(10,2)", "", "Recargo por estampar en esa zona."),
             ("is_active", "BOOLEAN", "", "Habilita o deshabilita la zona."),
         ]),
    dict(nombre="print_size", modulo="personalizacion",
         desc="Tamaños de estampado disponibles y su factor de costo.",
         campos=[
             ("id", "SERIAL", "PK", "Identificador del tamaño."),
             ("code", "VARCHAR(6)", "UQ", "A5, A4 o A3."),
             ("width_cm", "NUMERIC(5,1)", "", "Ancho del área de impresión."),
             ("height_cm", "NUMERIC(5,1)", "", "Alto del área de impresión."),
             ("cost_factor", "NUMERIC(4,2)", "", "Multiplicador sobre el costo base de la técnica."),
         ]),
    dict(nombre="design", modulo="personalizacion",
         desc="Diseño guardado por el cliente en Mis diseños, reutilizable en varias compras.",
         campos=[
             ("id", "SERIAL", "PK", "Identificador del diseño."),
             ("user_id", "INT", "FK -> app_user.id", "Cliente propietario."),
             ("name", "VARCHAR(80)", "", "Nombre que el cliente le puso al diseño."),
             ("image_url", "VARCHAR(250)", "", "Archivo subido por el cliente."),
             ("text_content", "VARCHAR(120)", "", "Texto del estampado, si lo hay."),
             ("font_family", "VARCHAR(40)", "", "Tipografía elegida."),
             ("text_color", "CHAR(7)", "", "Color del texto en hexadecimal."),
             ("created_at", "TIMESTAMP", "", "Fecha de creación."),
         ]),
    dict(nombre="customization", modulo="personalizacion",
         desc="Configuración concreta de estampado aplicada a una línea de carrito o de pedido.",
         campos=[
             ("id", "SERIAL", "PK", "Identificador de la personalización."),
             ("design_id", "INT", "FK -> design.id", "Diseño reutilizado; NULL si es de un solo uso."),
             ("technique_id", "INT", "FK -> print_technique.id", "Técnica de estampado elegida."),
             ("zone_id", "INT", "FK -> print_zone.id", "Zona de la prenda."),
             ("print_size_id", "INT", "FK -> print_size.id", "Tamaño del estampado."),
             ("image_url", "VARCHAR(250)", "", "Arte final enviado a producción."),
             ("text_content", "VARCHAR(120)", "", "Texto a estampar."),
             ("preview_url", "VARCHAR(250)", "", "Mockup generado para la vista previa."),
             ("extra_price", "NUMERIC(10,2)", "", "Recargo calculado y congelado al momento de agregar."),
             ("approval_status", "VARCHAR(12)", "", "PENDIENTE, APROBADO o RECHAZADO por el diseñador."),
             ("notes", "VARCHAR(250)", "", "Indicaciones del cliente o del diseñador."),
         ]),

    # --------------------------------------------------------------------- compra
    dict(nombre="cart", modulo="compra",
         desc="Carrito de compras. Soporta invitado (por session_id) y usuario autenticado.",
         campos=[
             ("id", "SERIAL", "PK", "Identificador del carrito."),
             ("user_id", "INT", "FK -> app_user.id", "Cliente dueño; NULL si es invitado."),
             ("session_id", "VARCHAR(64)", "", "JSESSIONID del invitado, para fusionar al iniciar sesión."),
             ("status", "VARCHAR(12)", "", "ACTIVO, CONVERTIDO o ABANDONADO."),
             ("created_at", "TIMESTAMP", "", "Fecha de creación."),
             ("updated_at", "TIMESTAMP", "", "Última modificación."),
             ("expires_at", "TIMESTAMP", "", "Vencimiento del carrito de invitado."),
         ]),
    dict(nombre="cart_item", modulo="compra",
         desc="Línea del carrito: una variante, con o sin personalización, y su cantidad.",
         campos=[
             ("id", "SERIAL", "PK", "Identificador de la línea."),
             ("cart_id", "INT", "FK -> cart.id", "Carrito al que pertenece."),
             ("variant_id", "INT", "FK -> product_variant.id", "Variante seleccionada."),
             ("customization_id", "INT", "FK -> customization.id", "Estampado aplicado; NULL si es lisa."),
             ("quantity", "INT", "", "Unidades. CHECK (quantity > 0)."),
             ("unit_price", "NUMERIC(10,2)", "", "Precio de la prenda al momento de agregar."),
             ("added_at", "TIMESTAMP", "", "Fecha en que se agrego."),
         ]),
    dict(nombre="wishlist_item", modulo="compra",
         desc="Lista de favoritos del cliente.",
         campos=[
             ("id", "SERIAL", "PK", "Identificador del favorito."),
             ("user_id", "INT", "FK -> app_user.id", "Cliente."),
             ("product_id", "INT", "FK -> product.id", "Producto marcado."),
             ("created_at", "TIMESTAMP", "", "Fecha en que se marcó."),
         ],
         restricciones=["UNIQUE (user_id, product_id)"]),
    dict(nombre="coupon", modulo="compra",
         desc="Cupones de descuento aplicables en el checkout.",
         campos=[
             ("id", "SERIAL", "PK", "Identificador del cupón."),
             ("code", "VARCHAR(20)", "UQ", "Código que digita el cliente."),
             ("description", "VARCHAR(150)", "", "Campaña a la que pertenece."),
             ("discount_type", "VARCHAR(10)", "", "PORCENTAJE o MONTO_FIJO."),
             ("discount_value", "NUMERIC(10,2)", "", "Valor del descuento."),
             ("min_purchase", "NUMERIC(10,2)", "", "Monto mínimo de compra exigido."),
             ("max_uses", "INT", "", "Tope global de canjes."),
             ("used_count", "INT", "", "Canjes realizados."),
             ("valid_from", "TIMESTAMP", "", "Inicio de vigencia."),
             ("valid_to", "TIMESTAMP", "", "Fin de vigencia."),
             ("is_active", "BOOLEAN", "", "Permite desactivar la campaña."),
         ]),
    dict(nombre="shipping_method", modulo="compra",
         desc="Modalidades de entrega y su costo.",
         campos=[
             ("id", "SERIAL", "PK", "Identificador del método."),
             ("name", "VARCHAR(60)", "", "Delivery Lima, Courier provincia o Recojo en tienda."),
             ("cost", "NUMERIC(10,2)", "", "Costo de envío."),
             ("estimated_days", "INT", "", "Días hábiles estimados de entrega."),
             ("coverage", "VARCHAR(80)", "", "Ámbito geográfico cubierto."),
             ("is_active", "BOOLEAN", "", "Habilita el método en el checkout."),
         ]),
    dict(nombre="orders", modulo="compra",
         desc="Cabecera del pedido. Se llama orders porque order es palabra reservada en SQL.",
         campos=[
             ("id", "SERIAL", "PK", "Identificador del pedido."),
             ("order_code", "VARCHAR(16)", "UQ", "Código visible para el cliente: CS-2026-000123."),
             ("user_id", "INT", "FK -> app_user.id", "Cliente que compra."),
             ("address_id", "INT", "FK -> address.id", "Dirección de entrega elegida."),
             ("shipping_method_id", "INT", "FK -> shipping_method.id", "Modalidad de entrega."),
             ("coupon_id", "INT", "FK -> coupon.id", "Cupón aplicado; NULL si no hubo."),
             ("status", "VARCHAR(15)", "", "PENDIENTE, PAGADO, EN_PRODUCCION, ENVIADO, ENTREGADO, CANCELADO."),
             ("subtotal", "NUMERIC(10,2)", "", "Suma de las líneas antes de descuento y envío."),
             ("discount_amount", "NUMERIC(10,2)", "", "Descuento aplicado por el cupón."),
             ("shipping_cost", "NUMERIC(10,2)", "", "Costo de envío congelado."),
             ("total_amount", "NUMERIC(10,2)", "", "Total a pagar."),
             ("customer_note", "VARCHAR(250)", "", "Indicación del cliente."),
             ("created_at", "TIMESTAMP", "", "Fecha del pedido."),
             ("updated_at", "TIMESTAMP", "", "Último cambio de estado."),
         ]),
    dict(nombre="order_item", modulo="compra",
         desc="Detalle del pedido. Guarda una foto de los datos para que el pedido no cambie si el catálogo cambia.",
         campos=[
             ("id", "SERIAL", "PK", "Identificador de la línea."),
             ("order_id", "INT", "FK -> orders.id", "Pedido al que pertenece."),
             ("variant_id", "INT", "FK -> product_variant.id", "Variante comprada (referencia)."),
             ("customization_id", "INT", "FK -> customization.id", "Estampado, si la prenda fue personalizada."),
             ("product_name", "VARCHAR(120)", "", "Nombre del producto al momento de comprar."),
             ("sku", "VARCHAR(30)", "", "SKU al momento de comprar."),
             ("size_label", "VARCHAR(6)", "", "Talla al momento de comprar."),
             ("color_name", "VARCHAR(30)", "", "Color al momento de comprar."),
             ("unit_price", "NUMERIC(10,2)", "", "Precio unitario congelado."),
             ("customization_price", "NUMERIC(10,2)", "", "Recargo de estampado congelado."),
             ("quantity", "INT", "", "Unidades compradas."),
             ("subtotal", "NUMERIC(10,2)", "", "(unit_price + customization_price) * quantity."),
         ]),
    dict(nombre="order_status_history", modulo="compra",
         desc="Trazabilidad: cada cambio de estado del pedido queda registrado con su responsable.",
         campos=[
             ("id", "BIGSERIAL", "PK", "Identificador del cambio."),
             ("order_id", "INT", "FK -> orders.id", "Pedido afectado."),
             ("previous_status", "VARCHAR(15)", "", "Estado anterior."),
             ("new_status", "VARCHAR(15)", "", "Estado nuevo."),
             ("changed_by", "INT", "FK -> app_user.id", "Usuario que ejecutó el cambio."),
             ("comment", "VARCHAR(250)", "", "Observación del cambio."),
             ("changed_at", "TIMESTAMP", "", "Fecha y hora del cambio."),
         ]),
    dict(nombre="payment", modulo="compra",
         desc="Registro del pago del pedido. En esta fase la pasarela es simulada.",
         campos=[
             ("id", "SERIAL", "PK", "Identificador del pago."),
             ("order_id", "INT", "FK -> orders.id", "Pedido pagado."),
             ("method", "VARCHAR(20)", "", "TARJETA, YAPE, PLIN, TRANSFERENCIA o CONTRAENTREGA."),
             ("transaction_code", "VARCHAR(40)", "", "Código devuelto por la pasarela simulada."),
             ("amount", "NUMERIC(10,2)", "", "Monto pagado."),
             ("status", "VARCHAR(12)", "", "PENDIENTE, APROBADO o RECHAZADO."),
             ("paid_at", "TIMESTAMP", "", "Fecha de acreditación."),
         ]),
    dict(nombre="review", modulo="compra",
         desc="Reseña de un producto. Solo la puede dejar quien compró esa línea (comprador verificado).",
         campos=[
             ("id", "SERIAL", "PK", "Identificador de la reseña."),
             ("product_id", "INT", "FK -> product.id", "Producto reseñado."),
             ("user_id", "INT", "FK -> app_user.id", "Autor de la reseña."),
             ("order_item_id", "INT", "FK -> order_item.id", "Compra que habilita la reseña."),
             ("rating", "SMALLINT", "", "Calificación. CHECK (rating BETWEEN 1 AND 5)."),
             ("title", "VARCHAR(80)", "", "Título de la reseña."),
             ("comment", "VARCHAR(500)", "", "Comentario del cliente."),
             ("is_approved", "BOOLEAN", "", "Moderación previa a la publicación."),
             ("created_at", "TIMESTAMP", "", "Fecha de publicación."),
         ],
         restricciones=["UNIQUE (user_id, order_item_id)"]),

    # -------------------------------------------------------------------- soporte
    dict(nombre="notification", modulo="soporte",
         desc="Bandeja de avisos del usuario: cambios de estado del pedido, aprobación de arte, promociones.",
         campos=[
             ("id", "BIGSERIAL", "PK", "Identificador del aviso."),
             ("user_id", "INT", "FK -> app_user.id", "Destinatario."),
             ("type", "VARCHAR(20)", "", "PEDIDO, DISENO, STOCK o PROMOCION."),
             ("title", "VARCHAR(100)", "", "Título del aviso."),
             ("message", "VARCHAR(300)", "", "Cuerpo del aviso."),
             ("related_order_id", "INT", "FK -> orders.id", "Pedido relacionado, si aplica."),
             ("is_read", "BOOLEAN", "", "Marca de lectura."),
             ("created_at", "TIMESTAMP", "", "Fecha de emisión."),
         ]),
    dict(nombre="audit_log", modulo="soporte",
         desc="Bitácora de acciones administrativas. Permite saber quién cambió qué y cuándo.",
         campos=[
             ("id", "BIGSERIAL", "PK", "Identificador del registro."),
             ("user_id", "INT", "FK -> app_user.id", "Usuario que ejecutó la acción."),
             ("entity", "VARCHAR(40)", "", "Tabla afectada."),
             ("entity_id", "INT", "", "Identificador del registro afectado."),
             ("action", "VARCHAR(10)", "", "CREAR, EDITAR, ELIMINAR o LOGIN."),
             ("old_value", "TEXT", "", "Estado anterior serializado en JSON."),
             ("new_value", "TEXT", "", "Estado nuevo serializado en JSON."),
             ("ip_address", "VARCHAR(45)", "", "IP de origen de la petición."),
             ("created_at", "TIMESTAMP", "", "Fecha y hora."),
         ]),
]

TABLA_POR_NOMBRE = {t["nombre"]: t for t in TABLAS}


def relaciones():
    """Devuelve la lista de (tabla_origen, campo, tabla_destino, campo_destino)."""
    out = []
    for t in TABLAS:
        for nombre, tipo, llave, _ in t["campos"]:
            if llave.startswith("FK"):
                destino = llave.split("->")[1].strip()
                td, cd = destino.split(".")
                out.append((t["nombre"], nombre, td, cd))
    return out


if __name__ == "__main__":
    print(f"{len(TABLAS)} tablas, {sum(len(t['campos']) for t in TABLAS)} campos, "
          f"{len(relaciones())} claves foráneas")
